# Generated by Django 3.2.13 on 2022-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
