# Generated by Django 3.2.13 on 2022-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermock',
            name='name',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
